### ISSUE TITLE
Input quantity on mix node

### ISSUE THREAD

**Issue by tenderbolton** [LaboratorioDeMedios/N.IMP_2.0#2]
A mix node can currently receive more than two inputs.

This is a bit weird, and even though the inputs are being displayed in the mixer's interface only the first two are taken into account during the mix.

Also, if you have three inputs and the first input has the same name as the last one, when you try to delete one of them both get deleted.

I think the mixer node should only have a maximum of two entries, and that the link deletion should be reviewed.

**Comment by nperi** [comment]
This was fixed. Mix simple blend now is limited to two inputs.
Link deletion was fixed
